# Generated by Django 5.0.4 on 2024-04-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='friend',
            new_name='friends',
        ),
    ]
